bnet/urls.py
from django.conf.urls import url

from . import views

app_name = 'bnet'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^all-hotels/$', views.all_hotels, name='all_hotels'),
    url(r'^hotels/$', views.HotelListView.as_view(), name='hotel_list'),
    url(r'^hotels/testing/$', views.test_hotel_list, name='testing_hotel_list'),
    url(r'^hotels/testing/(?P<pk>[0-9]+)/$', views.testing_hotel_details, name='testing_hotel_detail'),
    url(r'^hotels/(?P<pk>[0-9]+)/$', views.hotel_details, name='hotel_detail'),
    url(r'^hotels/sentiment/$', views.estimate_sentiment, name='estimate_sentiment')
]

mpdproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^bnet/', include('bnet.urls')),
    url(r'^django-sb-admin/', include('django_sb_admin.urls')),
    url(r'^admin/', admin.site.urls),
]

bnet/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models import Avg, Max
import math, itertools, re

# Create your models here.
class Hotel(models.Model):
    name = models.CharField(max_length=100)
    testing = models.BooleanField(default=False)

    def get_avg(self):
        avg = self.review_set.all().aggregate(Avg('overall'))
        if avg['overall__avg'] > 0:
            n = avg['overall__avg']
            return '%.1f' % round(n, 1)
        else: return None

    def get_stars(self):
        avg = float(self.get_avg())
        if avg >= 0:
            avg = int(avg*2)
            avg = float(avg) / 2
            full = int(avg)
            half = int(math.ceil(avg - full))
            empty = 5 - full - half;
            return {"full_stars":full,"half_star":half,"empty_stars":empty}
        else: return None

    def get_image_name(self):
        number = self.name[-1]
        return "exterior"+number+".jpg"

    def count_reviews(self):
        return len(self.review_set.all())

    def get_best_review(self):
        best = self.review_set.order_by('-overall')
        if len(best) > 0:
            return best[0]
        else: return None

    def get_worse_review(self):
        worse = self.review_set.order_by('overall')
        if len(worse) > 0:
            return worse[0]
        else: return None

    def __str__(self):
        return self.name

class Review(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    testing = models.BooleanField(default=False)
    content = models.TextField()
    overall = models.IntegerField()

    def get_stars(self):
        avg = float(self.overall)
        if avg >= 0:
            avg = int(avg*2)
            avg = float(avg) / 2
            full = int(avg)
            half = int(math.ceil(avg - full))
            empty = 5 - full - half;
            return {"full_stars":full,"half_star":half,"empty_stars":empty}
        else: return None

class ModelAccuracy(models.Model):
    hotel = models.ForeignKey(Hotel, on_delete=models.CASCADE)
    success = models.IntegerField(default=0)
    total_reviews = models.IntegerField(default=0)

    @property
    def success_ratio(self):
        if self.total_reviews > 0:
            return float(self.success) / float(self.total_reviews)
        else: return -1

class Term(models.Model):
    name = models.CharField(max_length=200)
    frequency = models.IntegerField(default=1)

    # Returns the top 1000 terms near to the term frequency average
    @staticmethod
    def get_dictionary():
        max_freq = Term.objects.all().aggregate(Max("frequency"))
        freq = max_freq["frequency__max"]*0.8
        pivot = str(freq)

        # 350 above pivot
        above = Term.objects.all().extra(where=["frequency >= "+pivot]).order_by("frequency")[:350]
        # 350 below pivot
        below = Term.objects.all().extra(where=["frequency < "+pivot]).order_by("-frequency")[:350]
        dictionary = set(itertools.chain(above, below))
        return dictionary

    def __str__(self):
        return self.name

class Skeleton(models.Model):
    managed = False

    @staticmethod
    def get_skeleton():
        dictionary = Term.get_dictionary()
        vertexes = ["overall".encode("utf-8")]
        edges = []
        for term in dictionary:
            vertexes.append(term.name.encode("utf-8"))
            edges.append(["overall".encode("utf-8"), term.name.encode("utf-8")])
        skeleton = {"V": vertexes, "E": edges}
        return skeleton

class BnetData(models.Model):
    managed = False

    @staticmethod
    def get_data():
        dictionary = Term.get_dictionary()
        reviews = Review.objects.all()[:10000]
        data = []
        for review in reviews:
            rdict = {"overall".encode("utf-8"): review.overall}
            for term in dictionary:
                matches = re.findall('\\b'+term.name+'\\b', review.content, flags=re.IGNORECASE)
                if len(matches)>0:
                    rdict[term.name.encode("utf-8")] = 1
                else:
                    rdict[term.name.encode("utf-8")] = 0
            data.append(rdict.copy())

        # workaround per assicurarsi che PGMLearner trovi
        # tutti i possibili valori assunti da un vertice
        for i in range(0,2):
            rdict = {"overall".encode("utf-8"): -1}
            for term in dictionary:
                rdict[term.name.encode("utf-8")] = i
            data.append(rdict.copy())

        return data

class BnetSettings(models.Model):
    key = models.TextField(unique=True)
    value = models.TextField()

    def __str__(self):
        return self.key

bnet/views.py
import os, re
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.core.urlresolvers import reverse
from django.views import generic
from django.db.models import Avg
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from libpgm.discretebayesiannetwork import *
from libpgm.pgmlearner import *
from libpgm.nodedata import *
from libpgm.graphskeleton import *
from libpgm.tablecpdfactorization import *

from .utils import BnetUtils
from .models import *

# Create your views here.
def index(request):
    hotels = Hotel.objects.filter(testing=False).count()
    reviews = Review.objects.filter(testing=False).count()
    counter = []
    for i in range(1,6):
        r = Review.objects.filter(overall=i).count()
        counter.append(r)

    terms = Term.objects.count()
    used_terms = len(Term.get_dictionary())
    performances = ModelAccuracy.objects.all()
    total_reviews = 0
    success = 0
    for p in performances:
        total_reviews += p.total_reviews
        success += p.success
    if total_reviews > 0:
        ratio = float(success) / float(total_reviews) * 100
    else: ratio = -1

    return render(request, "bnet/index.html", {
        'hotels': hotels,
        'reviews': reviews,
        'terms': terms,
        'used_terms': used_terms,
        'ratio': ratio,
        'testing_reviews': total_reviews,
        'total_reviews': total_reviews+reviews,
        'counter': counter,
        'nav_active': "index"})

def all_hotels(request):
    hotels = BnetUtils.parse_all_datasets("datasets/training")
    return render(request, "bnet/all-hotels.html", {'hotels': hotels})

def hotel_details(request, pk):
    hotel = get_object_or_404(Hotel, pk=pk)
    review_list = hotel.review_set.all()
    paginator = Paginator(review_list, 25) # Show 25 reviews per page

    page = request.GET.get('page')
    try:
        reviews = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        reviews = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        reviews = paginator.page(paginator.num_pages)


    return render(request, 'bnet/hotel-detail.html', {
        "hotel":hotel,
        "review_list":reviews,
        "page_obj":paginator,
        "nav_active":"hotel_detail"})

def testing_hotel_details(request, pk):
    hotel = get_object_or_404(Hotel, pk=pk)
    review_list = hotel.review_set.all()
    accuracy = hotel.modelaccuracy_set.all()[0]
    success_ratio = accuracy.success_ratio * 100
    paginator = Paginator(review_list, 25) # Show 25 reviews per page

    page = request.GET.get('page')
    try:
        reviews = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        reviews = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        reviews = paginator.page(paginator.num_pages)


    return render(request, 'bnet/test-hotel-detail.html', {
        "hotel":hotel,
        "success_ratio": success_ratio,
        "review_list":reviews,
        "page_obj":paginator,
        "nav_active":"hotel_detail"})

def estimate_sentiment(request):
    nd = NodeData()
    nd.load("nodedata.txt")
    gs = GraphSkeleton()
    gs.load("nodedata.txt")
    gs.toporder()
    dictionary = Term.get_dictionary()
    content = request.POST.get('content', '')
    review = dict()
    # review["content"] = u"Business hotel that also handles vacations Long weekend that was made all the more memorable with an attentive and courteous staff. Great location. Stayed in the North tower with a room overlooking the bay. Others have commented about dated rooms but this one was clean. Do park next door for $18.00. There's a catwalk to the second floor of the hotel. $38.00 a day for self park is a little much even for Seattle."
    # review["overall"] = 2
    # words = re.sub(ur"[^A-Za-z\s]", ' ', review["content"])
    # words = re.sub(ur" +", ' ', words)
    # words = words.encode("utf-8")
    # words = re.compile(r'\s+').split(words)
    # words = BnetUtils.process_testing_terms(words)
    # #words = map(str.lower, words)
    # words = list(set(words))
    evidence = dict()
    for term in dictionary:
        matches = re.findall('\\b'+term.name+'\\b', content, flags=re.IGNORECASE)
        if len(matches)>0:
            evidence[term.name.encode("utf-8")] = 1
        else:
            evidence[term.name.encode("utf-8")] = 0
    values = range(-1,6)
    results = dict()
    for val in values:
        query = dict(overall=[val])
        bn = DiscreteBayesianNetwork(gs, nd)
        fn = TableCPDFactorization(bn)
        result = fn.specificquery(query, evidence)
        results[val] = result
    est_value = max(results, key=results.get)
    return JsonResponse({"estimate": est_value})

def test_hotel_list(request):
    hotels = Hotel.objects.filter(testing=True)
    paginator = Paginator(hotels, 10) # Show 10 hotels per page

    page = request.GET.get('page')
    try:
        hotel_list = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        hotel_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        hotel_list = paginator.page(paginator.num_pages)

    return render(request, 'bnet/test-hotel-list.html', {
        "hotel_list":hotel_list,
        "page_obj":paginator,
        "nav_active":"testing_hotel_list"})

class HotelListView(generic.ListView):
    model = Hotel
    template_name = "bnet/hotel-list.html"
    paginate_by = 10
    def get_avg(hotel_id):
        return Hotel.objects.filter(pk=hotel_id).review_set.all().aggregate(Avg('overall'))
    def get_testing_hotels():
        return Hotel.objects.filter(testing=True)
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(HotelListView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['nav_active'] = "hotel_list"
        return context

class HotelDetailView(generic.DetailView):
    model = Hotel
    template_name = "bnet/hotel-detail.html"

bnet/templates/bnet/all-hotels.html
{% extends "bnet/base.html" %}
{% block sb_admin_title %}Tutti gli hotel{% endblock sb_admin_title %}
{% block sb_admin_subheading %}{% endblock sb_admin_subheading %}
{% block sb_admin_breadcrumb %}<i class="fa fa-dashboard"></i>  <a href="{% url 'bnet:index' %}">Panoramica</a>{% endblock sb_admin_breadcrumb %}
{% block sb_admin_breadcrumb_active %}
{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}

<h2>Sono state salvate le recensioni di {{hotels|length}} strutture</h2>
{% endblock sb_admin_content %}

bnet/templates/bnet/base.html
{% extends "django_sb_admin/base.html" %}
{% load static %}
{% block sb_admin_header %}<i class="fa fa-tripadvisor"></i> TripAdvisor sentiment analysis{% endblock sb_admin_header %}
{% block sb_admin_navbar_right %}{% endblock sb_admin_navbar_right %}
{% block sb_admin_sidebar %}<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        <li {% if nav_active == "index" %}class="active"{% endif %}>
            <a href="{% url "bnet:index" %}"><i class="fa fa-fw fa-dashboard"></i> Panoramica</a>
        </li>
        <li {% if nav_active == "hotel_list" %}class="active"{% endif %}>
            <a href="{% url "bnet:hotel_list" %}"><i class="fa fa-fw fa-bed"></i> Elenco hotel</a>
        </li>
        <li {% if nav_active == "testing_hotel_list" %}class="active"{% endif %}>
            <a href="{% url "bnet:testing_hotel_list" %}"><i class="fa fa-fw fa-check-circle"></i> Elenco hotel di test</a>
        </li>
    </ul>
</div>{% endblock sb_admin_sidebar %}
{% block sb_admin_content %}{% endblock sb_admin_content %}

bnet/templates/bnet/hotel-detail.html
{% extends "bnet/base.html" %}
{% load get_range %}
{% load static %}
{% block sb_admin_title %}
{% endblock sb_admin_title %}
{% block sb_admin_subheading %}{% endblock sb_admin_subheading %}
{% block sb_admin_breadcrumb %}<i class="fa fa-list"></i>  <a href="{% url 'bnet:hotel_list' %}">Elenco hotel</a>{% endblock sb_admin_breadcrumb %}
{% block sb_admin_breadcrumb_active %}
<i class="fa fa-angle-right"></i> <span class="hotel-title"><b>{{hotel.name}}</b></span>
{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}
<h2><span class="hotel-title">{{hotel.name}}</span></h2>
<p class="bigger">
  <span class="stars">
  {% for full_star in hotel.get_stars.full_stars|get_range %}
  <i class="fa fa-star"></i>
  {% endfor %}
  {% if hotel.get_stars.half_star > 0 %}
    <i class="fa fa-star-half-o"></i>
  {% endif %}
  {% for empty_star in hotel.get_stars.empty_stars|get_range %}
    <i class="fa fa-star-o"></i>
  {% endfor %}
  </span>
  <span class="count-reviews">({{hotel.count_reviews}} recensioni)</span>
</p>
<p class="dark grey"><i class="fa fa-map-marker"></i> Via Galattica per Autostoppisti, 42 - Loonquawl</p>
<div class="hotel-list-single row">
  <div class="col-lg-4 hotel-pic-wrapper">
    <div class="hotel-pic detail">
      <img src="{% static 'img/'%}{{hotel.get_image_name}}" style="height: 200px; width: 301px;">
    </div>
  </div>
  <div class="hotel-details col-lg-8">
    <div class="row">
      <div class="hotel-info col-lg-12">
        <h3><a href="{% url 'bnet:hotel_detail' hotel.pk %}">{{hotel.name}}</a></h3>
        {% load get_range %}
        <p class="big">
          <b>Media valutazioni: </b>
          <span class="stars">
          {% for full_star in hotel.get_stars.full_stars|get_range %}
          <i class="fa fa-star"></i>
          {% endfor %}
          {% if hotel.get_stars.half_star > 0 %}
            <i class="fa fa-star-half-o"></i>
          {% endif %}
          {% for empty_star in hotel.get_stars.empty_stars|get_range %}
            <i class="fa fa-star-o"></i>
          {% endfor %}
          </span>
          <span class="count-reviews">({{hotel.count_reviews}} recensioni)</span>
        </p>
        <div><b>Miglior recensione:</b></div>
        <div>
          <span class="stars">
          {% for full_star in hotel.get_best_review.get_stars.full_stars|get_range %}
          <i class="fa fa-star"></i>
          {% endfor %}
          {% if hotel.get_best_review.get_stars.half_star > 0 %}
            <i class="fa fa-star-half-o"></i>
          {% endif %}
          {% for empty_star in hotel.get_best_review.get_stars.empty_stars|get_range %}
            <i class="fa fa-star-o"></i>
          {% endfor %}
          </span>
        </div>
        <div><span class="review-text">&laquo;{{hotel.get_best_review.content|truncatechars:250}}&raquo;</span></div>
      </div>
    </div>
  </div>
</div>
<div class="hotel-list-single review row">
<div class="col-sm-12">
  <form id="add-review" method="post" action="{% url 'bnet:estimate_sentiment' %}">
  {% csrf_token %}
  <div class="form-group">
      <label for="content" class="col-sm-3 control-label">Lascia una recensione</label>
      <div class="col-sm-9">
        <textarea class="content form-control" name="content" rows="5" placeholder="Scrivi la tua recensione!"></textarea>
        <span class="form-stars-label">Valutazione suggerita: </span>
        <span class="stars big form-stars">
          <i class="fa fa-ban"></i>
        </span>
      </div>
  </div>
  </form>
</div>
<div class="col-xs-12">
<h3 class="green">{{hotel.count_reviews}} recensioni della community TripAdvisor</h3>
{% for review in review_list %}
{% if review.content|length > 0 %}
<div class="review row">
  <div class="col-lg-1">
    <span class="fa-stack-3x fa-3x">
      <i class="fa fa-circle fa-stack-2x grey"></i>
      <i class="fa fa-user fa-stack-1x white"></i>
    </span>
  </div>
  <div class="col-lg-11">
    <div class="review-box">
      <div class="review-box-inner">
        {% load get_range %}
        <span class="stars big">
        {% for full_star in review.get_stars.full_stars|get_range %}
        <i class="fa fa-star"></i>
        {% endfor %}
        {% if review.get_stars.half_star > 0 %}
          <i class="fa fa-star-half-o"></i>
        {% endif %}
        {% for empty_star in review.get_stars.empty_stars|get_range %}
          <i class="fa fa-star-o"></i>
        {% endfor %}
        </span>
        <p>{{review.content}}</p>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endfor %}
</div>
<div class="pagination">
    <span class="step-links">
        {% if review_list.has_previous %}
            <a href="?page={{ review_list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ review_list.number }} of {{ review_list.paginator.num_pages }}.
        </span>

        {% if review_list.has_next %}
            <a href="?page={{ review_list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
</div>
{% endblock sb_admin_content %}
{% block sb_admin_custom_js %}
<script type="text/javascript">
$(function() {
  var delay = (function(){
    var timer = 0;
    return function(callback, ms){
      clearTimeout (timer);
      timer = setTimeout(callback, ms);
    };
  })();
  $("textarea[name='content']").keyup(function() {
      delay(function(){
        var content = $("textarea[name='content']").val();
        $.ajax({
          type: "POST",
          url: "{% url 'bnet:estimate_sentiment' %}",
          data: {"content": content},
          beforeSend: function(xhr, settings) {
            var csrftoken = $("input[name='csrfmiddlewaretoken']").val()
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
            $(".form-stars").html('<i class="fa fa-spinner fa-pulse fa-fw"></i>');
          },
          success: function(result) {
            var stars = result.estimate;
            if(stars>0) {
              var html = "";
              for (var s=0;s<stars;s++) {
                html += '<i class="fa fa-star"></i>'
              }
              for (var h=0;h<5-stars;h++) {
                html += '<i class="fa fa-star-o"></i>'
              }
              $(".form-stars").html(html);
            } else {
              $(".form-stars").html("<i class='fa fa-lightbulb-o'></i> Non riesco a capire cosa ne pensi. Dimmi qualcosa di più!");
            }
          },
          dataType: 'json'
        });
      }, 500 );
  });
});
</script>
{% endblock sb_admin_custom_js %}

bnet/templates/bnet/hotel-list.html
{% extends "bnet/base.html" %}
{% load static %}
{% block sb_admin_title_text %}Elenco hotel{% endblock sb_admin_title_text %}
{% block sb_admin_subheading %}{% endblock sb_admin_subheading %}
{% block sb_admin_breadcrumb %}<i class="fa fa-dashboard"></i>  <a href="{% url 'bnet:index' %}">Panoramica</a>{% endblock sb_admin_breadcrumb %}
{% block sb_admin_breadcrumb_active %}
<i class="fa fa-angle-right"></i> <span class="hotel-title"><b>Elenco hotel</b></span>
{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}

{% for hotel in hotel_list %}
<div class="hotel-list-single row">
  <div class="col-lg-2 hotel-pic-wrapper">
    <div class="hotel-pic">
      <img src="{% static 'img/'%}{{hotel.get_image_name}}" style="height: 200px; width: 301px; margin-left: -70px;">
    </div>
  </div>
  <div class="hotel-details col-lg-10">
    <div class="row">
      <div class="hotel-info col-lg-8">
        <h3><a href="{% url 'bnet:hotel_detail' hotel.pk %}">{{hotel.name}}</a></h3>
        {% load get_range %}
        <p class="big">
          <b>Media valutazioni: </b>
          <span class="stars">
          {% for full_star in hotel.get_stars.full_stars|get_range %}
          <i class="fa fa-star"></i>
          {% endfor %}
          {% if hotel.get_stars.half_star > 0 %}
            <i class="fa fa-star-half-o"></i>
          {% endif %}
          {% for empty_star in hotel.get_stars.empty_stars|get_range %}
            <i class="fa fa-star-o"></i>
          {% endfor %}
          </span>
          <span class="count-reviews">({{hotel.count_reviews}} recensioni)</span>
        </p>
        <div><b>Miglior recensione:</b></div>
        <div>
          <span class="stars">
          {% for full_star in hotel.get_best_review.get_stars.full_stars|get_range %}
          <i class="fa fa-star"></i>
          {% endfor %}
          {% if hotel.get_best_review.get_stars.half_star > 0 %}
            <i class="fa fa-star-half-o"></i>
          {% endif %}
          {% for empty_star in hotel.get_best_review.get_stars.empty_stars|get_range %}
            <i class="fa fa-star-o"></i>
          {% endfor %}
          </span>
        </div>
        <div><span class="review-text">&laquo;{{hotel.get_best_review.content|truncatechars:150}}&raquo;</span></div>
      </div>
      <div class="hotel-links col-lg-4">
        <button class="ui_button original large w100p" onclick="window.location = '{% url 'bnet:hotel_detail' hotel.pk %}'">Dettagli hotel</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
{% if is_paginated %}
<div class="container-fluid">
  <div class="row hotel-list-single">
    <div class="col-lg-12">
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a class="pull-left ui_button primary" href="{% url 'bnet:hotel_list' %}?page={{ page_obj.previous_page_number }}"><i class="fa fa-angle-left"></i> previous</a>
                {% endif %}
                {% if not page_obj.has_previous %}
                    <button disabled class="pull-left ui_button primary disabled"><i class="fa fa-ban"></i> precedente</button>
                {% endif %}
                <span class="page-current">
                    Pagina {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a class="pull-right ui_button primary" href="{% url 'bnet:hotel_list' %}?page={{ page_obj.next_page_number }}">successiva <i class="fa fa-angle-right"></i></a>
                {% endif %}
            </span>
        </div>
      </div>
    </div>
</div>
    {% endif %}
{% endblock sb_admin_content %}

bnet/templates/bnet/test-hotel-list.html
{% extends "bnet/base.html" %}
{% load static %}
{% block sb_admin_title_text %}Elenco hotel di test{% endblock sb_admin_title_text %}
{% block sb_admin_subheading %}{% endblock sb_admin_subheading %}
{% block sb_admin_breadcrumb %}<i class="fa fa-dashboard"></i>  <a href="{% url 'bnet:index' %}">Panoramica</a>{% endblock sb_admin_breadcrumb %}
{% block sb_admin_breadcrumb_active %}
<i class="fa fa-angle-right"></i> <span class="hotel-title"><b>Elenco hotel di test</b></span>
{% endblock sb_admin_breadcrumb_active %}
{% block sb_admin_content %}

{% for hotel in hotel_list %}
<div class="hotel-list-single row">
  <div class="col-lg-2 hotel-pic-wrapper">
    <div class="hotel-pic">
      <img src="{% static 'img/'%}{{hotel.get_image_name}}" style="height: 200px; width: 301px; margin-left: -70px;">
    </div>
  </div>
  <div class="hotel-details col-lg-10">
    <div class="row">
      <div class="hotel-info col-lg-8">
        <h3><a href="{% url 'bnet:testing_hotel_detail' hotel.pk %}">{{hotel.name}}</a></h3>
        {% load get_range %}
        <p class="big">
          <b>Media valutazioni: </b>
          <span class="stars">
          {% for full_star in hotel.get_stars.full_stars|get_range %}
          <i class="fa fa-star"></i>
          {% endfor %}
          {% if hotel.get_stars.half_star > 0 %}
            <i class="fa fa-star-half-o"></i>
          {% endif %}
          {% for empty_star in hotel.get_stars.empty_stars|get_range %}
            <i class="fa fa-star-o"></i>
          {% endfor %}
          </span>
          <span class="count-reviews">({{hotel.count_reviews}} recensioni)</span>
        </p>
        <div><b>Miglior recensione:</b></div>
        <div>
          <span class="stars">
          {% for full_star in hotel.get_best_review.get_stars.full_stars|get_range %}
          <i class="fa fa-star"></i>
          {% endfor %}
          {% if hotel.get_best_review.get_stars.half_star > 0 %}
            <i class="fa fa-star-half-o"></i>
          {% endif %}
          {% for empty_star in hotel.get_best_review.get_stars.empty_stars|get_range %}
            <i class="fa fa-star-o"></i>
          {% endfor %}
          </span>
        </div>
        <div><span class="review-text">&laquo;{{hotel.get_best_review.content|truncatechars:150}}&raquo;</span></div>
      </div>
      <div class="hotel-links col-lg-4">
        <button class="ui_button original large w100p" onclick="window.location = '{% url 'bnet:testing_hotel_detail' hotel.pk %}'">Dettagli hotel</button>
      </div>
    </div>
  </div>
</div>
{% endfor %}
<div class="container-fluid">
  <div class="row hotel-list-single">
    <div class="col-lg-12">
        <div class="pagination">
            <span class="page-links">
                {% if hotel_list.has_previous %}
                    <a class="pull-left ui_button primary" href="{% url 'bnet:testing_hotel_list' %}?page={{ hotel_list.previous_page_number }}"><i class="fa fa-angle-left"></i> previous</a>
                {% endif %}
                {% if not hotel_list.has_previous %}
                    <button disabled class="pull-left ui_button primary disabled"><i class="fa fa-ban"></i> precedente</button>
                {% endif %}
                <span class="page-current">
                    Pagina {{ hotel_list.number }} di {{ hotel_list.paginator.num_pages }}.
                </span>
                {% if hotel_list.has_next %}
                    <a class="pull-right ui_button primary" href="{% url 'bnet:testing_hotel_list' %}?page={{ hotel_list.next_page_number }}">successiva <i class="fa fa-angle-right"></i></a>
                {% endif %}
            </span>
        </div>
      </div>
    </div>
</div>
{% endblock sb_admin_content %}